pokemons = [
    {
        "name": "Gengar",
        "number": 94,
        "types": ["fantasma", "veneno"],
        "weaknesses": ["psiquico", "tierra", "fantasma", "siniestro"],
        "mega": True,
        "gigamax": True,
    },
    {
        "name": "Charizard",
        "number": 6,
        "types": ["fuego", "volador"],
        "weaknesses": ["roca", "agua", "electrico"],
        "mega": True,
        "gigamax": True,
    },
    {
        "name": "aceroix",
        "number": 208,
        "types": ["acero", "tierra"],
        "weaknesses": ["fuego", "agua", "lucha", "tierra"],
        "mega": True,
        "gigamax": False,
    },
    {
        "name": "Pikachu",
        "number": 25,
        "types": ["electrico"],
        "weaknesses": ["tierra"],
        "mega": False,
        "gigamax": True,
    },
    {
        "name": "Jolteon",
        "number": 135,
        "types": ["electrico"],
        "weaknesses": ["tierra"],
        "mega": False,
        "gigamax": False,
    },
    {
        "name": "Lycanroc",
        "number": 745,
        "types": ["roca"],
        "weaknesses": ["agua", "planta", "lucha", "tierra", "acero"],
        "mega": False,
        "gigamax": False,
    },
    {
        "name": "Tyrantrum",
        "number": 697,
        "types": ["roca", "dragon"],
        "weaknesses": ["hielo", "lucha", "tierra", "dragon", "acero", "hada"],
        "mega": False,
        "gigamax": False,
    },
    {
        "name": "Mimikyu",
        "number": 778,
        "types": ["fantasma", "hada"],
        "weaknesses": ["fantasma", "acero"],
        "mega": False,
        "gigamax": True,
    },
    {
        "name": "Arcanine",
        "number": 59,
        "types": ["fuego"],
        "weaknesses": ["agua", "tierra", "roca"],
        "mega": False,
        "gigamax": False,
    },
    {
        "name": "Magnezone",
        "number": 462,
        "types": ["electrico", "acero"],
        "weaknesses": ["tierra", "fuego", "lucha"],
        "mega": False,
        "gigamax": False,
    },
    {
        "name": "Duskull",
        "number": 355,
        "types": ["fantasma"],
        "weaknesses": ["fantasma", "siniestro"],
        "mega": False,
        "gigamax": False,
    },
    {
        "name": "Scizor",
        "number": 212,
        "types": ["bug", "acero"],
        "weaknesses": ["fuego"],
        "mega": True,
        "gigamax": False,
    },
    {
        "name": "Rotom",
        "number": 479,
        "types": ["electrico", "fantasma"],
        "weaknesses": ["fantasma", "siniestro", "tierra"],
        "mega": False,
        "gigamax": False,
    },
    {
        "name": "Houndoom",
        "number": 229,
        "types": ["siniestro", "fuego"],
        "weaknesses": ["agua", "lucha", "tierra", "roca"],
        "mega": True,
        "gigamax": False,
    },
    {
        "name": "Aegislash",
        "number": 681,
        "types": ["acero", "fantasma"],
        "weaknesses": ["fantasma", "fuego", "siniestro", "tierra"],
        "mega": False,
        "gigamax": False,
    },
    {
        "name": "Eelektross",
        "number": 604,
        "types": ["electrico"],
        "weaknesses": [],  # habilidad levitate
        "mega": False,
        "gigamax": False,
    },
    {
        "name": "Lampent",
        "number": 608,
        "types": ["fantasma", "fuego"],
        "weaknesses": ["fantasma", "agua", "roca", "siniestro", "tierra"],
        "mega": False,
        "gigamax": False,
    },
    {
        "name": "Skarmory",
        "number": 227,
        "types": ["acero", "volador"],
        "weaknesses": ["electrico", "fuego"],
        "mega": False,
        "gigamax": False,
    },
    {
        "name": "Chandelure",
        "number": 609,
        "types": ["fantasma", "fuego"],
        "weaknesses": ["fantasma", "agua", "roca", "siniestro", "tierra"],
        "mega": False,
        "gigamax": False,
    },
    {
        "name": "Luxray",
        "number": 405,
        "types": ["electrico"],
        "weaknesses": ["tierra"],
        "mega": False,
        "gigamax": False,
    },
]
